version: 2.1

#commands:
#  print_pipeline_id:
#    description: "a simple command to "
#    parameters:
#      to:
#        type: string
#        default: "No $CIRCLE_WORKFLOW_ID available"
#    steps:
#      - run: echo "The Circle CI Workflow ID is << parameters.to >>"

executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0
  #  working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - run:
          name: Upload Failed Tests
          command: echo "Something has gone wrong"
          when: on_fail

  test:
    executor: my-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      - run:
          name: Upload Failed Tests
          command: echo "Something has gone wrong"
          when: on_fail

  analyse:
    executor: my-executor
    steps:
      - checkout
      - run: npm audit
      - run:
          name: Upload Failed Tests
          command: echo "Something has gone wrong"
          when: on_fail

workflows:
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
